# Uncomment the next line to define a global platform for your project
# platform :iOS, ’4.3’

target 'stakeMyself' do

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for stakeMyself
	pod 'Firebase/Core'
	pod 'Firebase/Database’
    pod 'Firebase/Auth’
    

end
